# Libs

In [56]:
import pandas as pd
import numpy as np
import random
random.randint

<bound method Random.randint of <random.Random object at 0x000001FAECB7AC20>>

<h1>Numpy x Lista</h1>

In [3]:
s_lista = [[10,6,4,8], [5,6,5,6]]
s_lista 

[[10, 6, 4, 8], [5, 6, 5, 6]]

In [4]:
type(s_lista)

list

**Numpy não trabalha com listas (list), é necessário converter para Array (ndarray)**

In [5]:
s_vetor = np.array(s_lista)
s_vetor

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6]])

In [6]:
type(s_vetor)

numpy.ndarray

**Exemplo em manipulação de Lista**

In [7]:
s_lista[0][3]
s_lista[0][-1]

8

**Exemplo em manipulação no Array**

In [8]:
#[Semestre, Prova]
s_vetor[0,-1]

np.int64(8)

In [9]:
type([1,'0'][0])

int

In [10]:
type([1,'0'][1])

str

In [11]:
s_vetor.dtype

dtype('int64')

In [12]:
type(np.array([1,'0'])[0])

numpy.str_

In [13]:
s_vetor.ndim

2

**Soma em Lista**

In [14]:
#Não é possível somar em uma Lista
s_lista+1

TypeError: can only concatenate list (not "int") to list

In [ ]:
s_vetor

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6]])

In [ ]:
#No Array ele soma por cada elemento
s_vetor+1

array([[11,  7,  5,  9],
       [ 6,  7,  6,  7]])

**Realizando alterações dentro da Lista**

In [ ]:
resultado = []
for lista in s_lista:
    for item in lista:
        print(item)

10
6
4
8
5
6
5
6


In [ ]:
resultado = []
for lista in range(len(s_lista)):
    resultado.append([])
    for item in s_lista[lista]:
        item+=2
        resultado[lista].append(item)
        
print(resultado)

[[12, 8, 6, 10], [7, 8, 7, 8]]


In [ ]:
print(s_lista)

[[10, 6, 4, 8], [5, 6, 5, 6]]


<h1>Numpy</h1>

In [16]:
s_vetor

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6]])

In [15]:
s_vetor %2 ==0

array([[ True,  True,  True,  True],
       [False,  True, False,  True]])

In [17]:
#mascara
s_vetor[s_vetor % 2 ==0]

array([10,  6,  4,  8,  6,  6])

In [ ]:
#Impar utilizando Not
s_vetor[~s_vetor % 2 ==0]

array([5, 5])

## Operacoes Booleanas
- not: ~
- and: &
- or:  |
- xor: ^

In [19]:
a_lista = [
    s_lista,
    s_lista
]
a_lista

[[[10, 6, 4, 8], [5, 6, 5, 6]], [[10, 6, 4, 8], [5, 6, 5, 6]]]

In [20]:
a_vetor = np.array(a_lista)
a_vetor

array([[[10,  6,  4,  8],
        [ 5,  6,  5,  6]],

       [[10,  6,  4,  8],
        [ 5,  6,  5,  6]]])

In [ ]:
array([
        [[10,  6,  4,  8],
        [ 5,  6,  5,  6]],

       [
        [10,  6,  4,  8],
        [ 5,  6,  5,  6]
        ]
       ]
      
      )

## Seleção

In [24]:
#[ano, semestre, prova]

a_vetor[1,0,3]

np.int64(8)

In [25]:
a_vetor

array([[[10,  6,  4,  8],
        [ 5,  6,  5,  6]],

       [[10,  6,  4,  8],
        [ 5,  6,  5,  6]]])

In [ ]:
#Somando 1 no 2º Semestre
a_vetor[1,:,:] = a_vetor[1,:,:] + 1
a_vetor

array([[[10,  6,  4,  8],
        [ 5,  6,  5,  6]],

       [[11,  7,  5,  9],
        [ 6,  7,  6,  7]]])

In [ ]:
a_vetor[:,:,-1]

array([[4, 5],
       [5, 6]])

In [31]:
ano = a_vetor[0,1,1]
semestre = a_vetor[0,0,1]
prova = [0,1,2]


In [ ]:
ano

[0, 1, 2]

In [33]:
semestre

np.int64(6)

In [34]:
prova

[0, 1, 2]

In [35]:
np.zeros([2,2,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
np.full([2,2,4],2)

array([[[2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [39]:
np.full([2,2,4],'a')

array([[['a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a']],

       [['a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a']]], dtype='<U1')

In [43]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [44]:
np.arange(2,18,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
#Random com INT
np.random.randint(0,11, (2,2,4))

array([[[ 3,  3,  9,  8],
        [10,  4,  5, 10]],

       [[ 1,  5,  9,  2],
        [ 3,  3,  9,  8]]], dtype=int32)

In [ ]:
#Random com FLOAT
np.round(np.random.uniform(0,11, (2,2,4)),2)

array([[[10.19,  8.9 ,  6.73,  3.89],
        [10.04,  7.31,  6.  ,  2.47]],

       [[ 9.59,  2.44,  3.73,  2.81],
        [ 5.75,  9.59,  8.57,  6.27]]])

In [60]:
np.round(np.random.uniform(0,11, (2,2,4)),2)

array([[[ 6.39,  8.38,  6.49,  2.16],
        [ 4.94,  8.92,  8.3 ,  6.51]],

       [[ 6.09,  2.29,  7.86,  7.14],
        [ 9.41,  4.56, 10.61,  8.53]]])

In [57]:
np.random.choice(['A','R'],(2,2,4))

array([[['A', 'R', 'R', 'R'],
        ['R', 'R', 'A', 'A']],

       [['A', 'A', 'A', 'A'],
        ['A', 'R', 'R', 'R']]], dtype='<U1')