In [3]:
import numpy as np
import random
random.randint

<bound method Random.randint of <random.Random object at 0x0000024EEF7A3800>>

1. Utilizando a biblioteca numpy siga as instruções abaixo:
  1. Crie um array 6x6 preenchido com zero
  2. Preencha o centro desse array com um array 4x4 preenchido com uns
  3. Preencha o centro desse array com um array 2x2 preenchido com dois
  4. Gere um segundo array 6x6 com números inteiros aleatórios entre 0 e 2. (semente 0)
  5. Subtraia o primeiro array pelo segundo

In [4]:
#1 Array preenchido com 6x0

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
 #1. Crie um array 6x6 preenchido com zero 2d
 array_1f = np.zeros(shape=(6,6))
 array_1f

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
 #1. Crie um array 6x6 preenchido com zero 2d (Convertendo para INT para retirar ".")
 array_1 = np.zeros(shape=(6,6), dtype=int)
 array_1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
 #1. Crie um array 6x6 preenchido com zero 3d
array6 = np.full([6,1,6],0)
array6

array([[[0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0]]])

In [10]:
#2. Preencha o centro desse array com um array 4x4 preenchido com uns

In [22]:
for i in array_1:
    print(i)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


In [25]:
print(array_1[1])

[0. 0. 0. 0. 0. 0.]


In [24]:
 array_4 = np.zeros(shape=(4,4))
 array_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])